sudo: required

services:
  - docker

env:
  - IMAGE_NAME=charlescatta/dswp

before_script:
  - docker --version
  - docker pull "${IMAGE_NAME}:latest" || true

script:
  - COMMIT_HASH="$(git rev-parse --short HEAD)"
  - docker build --cache-from "${IMAGE_NAME}:latest" --tag "${IMAGE_NAME}:${COMMIT_HASH}" .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker tag "${IMAGE_NAME}:${COMMIT_HASH}" "${IMAGE_NAME}:latest"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${COMMIT_HASH}"
  on:
    branch: master
