sudo: 'required'

services:
    - 'docker'

before_install:
  - docker build --no-cache -t ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} .

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} ${TRAVIS_REPO_SLUG}:latest
  - docker push ${TRAVIS_REPO_SLUG}
